AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Alexa AI Skill with Multi-Provider Support

Globals:
  Function:
    Timeout: 30
    MemorySize: 256

Resources:
  MemoryBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  AISkillFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/
      Handler: index.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          AI_MODEL: "google:gemini-2.5-flash"
          GOOGLE_GENERATIVE_AI_API_KEY: ""
          OPENAI_API_KEY: ""
          ANTHROPIC_API_KEY: ""
          TAVILY_API_KEY: ""
          MEMORY_BUCKET: !Ref MemoryBucket
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref MemoryBucket
      Events:
        AlexaEndpoint:
          Type: HttpApi
          Properties:
            Path: /alexa
            Method: POST
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - src/index.ts

Outputs:
  AlexaEndpointUrl:
    Description: API Gateway endpoint URL for Alexa skill
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/alexa"
  AISkillFunction:
    Description: Lambda Function ARN
    Value: !GetAtt AISkillFunction.Arn
